POST http://localhost:9009/api/stripe/webhook
Content-Type: application/json

{
  "id": "evt_3KVUC8HAwJOu5brr0xkqwqz8",
  "object": "event",
  "api_version": "2020-08-27",
  "created": 1645420341,
  "data": {
    "object": {
      "id": "ch_3KVUC8HAwJOu5brr0CC2OHcM",
      "object": "charge",
      "amount": 105,
      "amount_captured": 105,
      "amount_refunded": 0,
      "application": "ca_9gE5S2SsGFB6QVRazAnjZfdeGmeiAYOq",
      "application_fee": null,
      "application_fee_amount": 2,
      "balance_transaction": "txn_3KVUC8HAwJOu5brr0zR5Z0WO",
      "billing_details": {
        "address": {
          "city": null,
          "country": null,
          "line1": null,
          "line2": null,
          "postal_code": "46814",
          "state": null
        },
        "email": null,
        "name": null,
        "phone": null
      },
      "calculated_statement_descriptor": "IMPACT UPGRADE",
      "captured": true,
      "created": 1645420340,
      "currency": "usd",
      "customer": "cus_Kr9kQEoDAfiLpe",
      "description": null,
      "destination": null,
      "dispute": null,
      "disputed": false,
      "failure_code": null,
      "failure_message": null,
      "fraud_details": {
      },
      "invoice": null,
      "livemode": false,
      "metadata": {
        "Form": "Donation Form: Donate Online",
        "Subselection Key": "Fund",
        "Subselection Value": "general"
      },
      "on_behalf_of": null,
      "order": null,
      "outcome": {
        "network_status": "approved_by_network",
        "reason": null,
        "risk_level": "normal",
        "risk_score": 17,
        "seller_message": "Payment complete.",
        "type": "authorized"
      },
      "paid": true,
      "payment_intent": null,
      "payment_method": "card_1KBRRLHAwJOu5brrDlEkOeZ6",
      "payment_method_details": {
        "card": {
          "brand": "visa",
          "checks": {
            "address_line1_check": null,
            "address_postal_code_check": "pass",
            "cvc_check": null
          },
          "country": "US",
          "exp_month": 12,
          "exp_year": 2022,
          "fingerprint": "WHTBeQ5HmOeHlWfu",
          "funding": "credit",
          "installments": null,
          "last4": "4242",
          "network": "visa",
          "three_d_secure": null,
          "wallet": null
        },
        "type": "card"
      },
      "receipt_email": null,
      "receipt_number": null,
      "receipt_url": "https://pay.stripe.com/receipts/acct_1Imqu3HAwJOu5brr/ch_3KVUC8HAwJOu5brr0CC2OHcM/rcpt_LBrwxz7GG4Cvdb82tvlUvY1NKkJDVvr",
      "refunded": false,
      "refunds": {
        "object": "list",
        "data": [
        ],
        "has_more": false,
        "total_count": 0,
        "url": "/v1/charges/ch_3KVUC8HAwJOu5brr0CC2OHcM/refunds"
      },
      "review": null,
      "shipping": null,
      "source": {
        "id": "card_1KBRRLHAwJOu5brrDlEkOeZ6",
        "object": "card",
        "address_city": null,
        "address_country": null,
        "address_line1": null,
        "address_line1_check": null,
        "address_line2": null,
        "address_state": null,
        "address_zip": "46814",
        "address_zip_check": "pass",
        "brand": "Visa",
        "country": "US",
        "customer": "cus_Kr9kQEoDAfiLpe",
        "cvc_check": null,
        "dynamic_last4": null,
        "exp_month": 12,
        "exp_year": 2022,
        "fingerprint": "WHTBeQ5HmOeHlWfu",
        "funding": "credit",
        "last4": "4242",
        "metadata": {
        },
        "name": null,
        "tokenization_method": null
      },
      "source_transfer": null,
      "statement_descriptor": null,
      "statement_descriptor_suffix": null,
      "status": "succeeded",
      "transfer_data": null,
      "transfer_group": null
    }
  },
  "livemode": false,
  "pending_webhooks": 1,
  "request": {
    "id": "req_PaCklxVO5VfhQB",
    "idempotency_key": "d49fe640-1b1a-4d8a-8e73-793fb6949cc3"
  },
  "type": "charge.succeeded"
}

###
