package com.impactupgrade.nucleus.model;

public enum PaymentGatewayEventType {
  PAYMENT_SUCCESS, CHARGE_SUCCESS, PAYMENT_FAILURE, CHARGE_FAILURE, SUBSCRIPTION_CLOSED, SUBSCRIPTION_CREATED, PAYOUT_SUCCESS, SOURCE_EXPIRING, CHARGE_REFUNDED
}
