# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v18
      with:
        servers: '[{ "id": "github", "username": "impactupgrade-github", "password": "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" }]'
        output_file: ~/.m2/settings.xml
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: mvn --update-snapshots clean verify -P it,sandbox
